# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: deploy-online-endpoint-pipeline

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml
  - name: version
    value: python-sdk-v2
  - name: endpoint_name
    value: taxi-online-$(namespace)$(postfix)$(environment)

trigger: none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: mlops-templates # Template Repo
      name: mlops-templates
      type: git
      ref: main

stages:
  - stage: CreateOnlineEndpoint
    displayName: Create/Update Online Endpoint
    jobs:
      - job: DeployOnlineEndpoint
        steps:
          - checkout: self
            path: s/
          - task: Bash@3
            displayName: "Create checkout repository folder(s)"
            inputs:
              targetType: "inline"
              script: |
                set -e
                mkdir "$(Build.Repository.Name)"
                mkdir "mlops-templates"
          - checkout: mlops-templates
            path: s/templates/
          - template: templates/aml-cli-v2/install-az-cli.yml@mlops-templates
          - template: templates/aml-cli-v2/install-aml-cli.yml@mlops-templates
          - template: templates/aml-cli-v2/connect-to-workspace.yml@mlops-templates
          - template: templates/${{ variables.version }}/create-online-endpoint.yml@mlops-templates
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              endpoint_description: "Taxi Online Endpoint"
              auth_mode: "aml_token"
          - template: templates/${{ variables.version }}/create-online-deployment.yml@mlops-templates
            parameters:
              deployment_name: taxi-online-dp
              endpoint_name: "${{ variables.endpoint_name }}"
              model_path: "taxi-model@latest"
              traffic_allocation: 100
          - template: templates/${{ variables.version }}/test-online-endpoint.yml@mlops-templates
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              sample_request: data/taxi-request.json
