# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: deploy-model-training-pipeline

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml
  - name: version
    value: aml-cli-v2

trigger: none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: mlops-templates # Template Repo
      name: mlops-templates
      type: git
      ref: main

stages:
  - stage: DeployTrainingPipeline
    displayName: Deploy Training Pipeline
    jobs:
      - job: DeployTrainingPipeline
        steps:
          - checkout: self
            path: s/
          - task: Bash@3
            displayName: "Create checkout repository folder(s)"
            inputs:
              targetType: "inline"
              script: |
                set -e
                mkdir "$(Build.Repository.Name)"
                mkdir "mlops-templates"
          - checkout: mlops-templates
            path: s/templates/
          - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
          - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
          - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
          - template: templates/${{ variables.version }}/create-compute.yml@mlops-templates
            parameters:
              cluster_name: gpu-cluster
              size: Standard_NC6
              min_instances: 0
              max_instances: 1
              cluster_tier: dedicated
          - template: templates/${{ variables.version }}/register-environment.yml@mlops-templates
            parameters:
              build_type: docker
              environment_name: nvidia_pytorch # Not used for docker builds
              environment_file: mlops/azureml/train/train-env.yaml
          - template: templates/${{ variables.version }}/register-dataset.yml@mlops-templates
            parameters:
              data_type: training
              environment_file: mlops/azureml/train/create_stanford_dogs_dataset.yaml
          - template: templates/${{ variables.version }}/run-pipeline.yml@mlops-templates
            parameters:
              pipeline_file: mlops/azureml/train/pipeline.yaml
              experiment_name: $(environment)_cv_train_$(Build.SourceBranchName)
              display_name: $(environment)_cv_run_$(Build.BuildID)
