$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: dogs-classifier-online
model: azureml:resnet-dogs-classifier@latest
instance_type: Standard_DS2_v2
instance_count: 1
