# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: deploy-model-training-pipeline

variables:
  - template: ../../config-aml.yml
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml
  - name: version
    value: python-sdk-v1

trigger: none

pool:
  vmImage: $(ap_vm_image)

resources:
  repositories:
    - repository: mlops-templates # Template Repo
      name: mlops-templates
      type: git
      ref: main

stages:
  - stage: DeployTrainingPipeline
    displayName: Deploy Training Pipeline
    jobs:
      - job: DeployTrainingPipeline
        steps:
          - checkout: self
            path: s/
          - task: Bash@3
            displayName: "Create checkout repository folder(s)"
            inputs:
              targetType: "inline"
              script: |
                set -e
                mkdir "$(Build.Repository.Name)"
                mkdir "mlops-templates"
          - checkout: mlops-templates
            path: s/templates/
          - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
          - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
          - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
          - template: templates/${{ variables.version }}/create-environment.yml@mlops-templates
            parameters:
              environment_name: $(training_env_name)
              build_type: "conda"
              environment_file: $(training_env_conda_yaml)
              enable_monitoring: $(enable_monitoring)
          - template: templates/${{ variables.version }}/register-dataset.yml@mlops-templates
            parameters:
              data_type: training
          - template: templates/${{ variables.version }}/get-compute.yml@mlops-templates
            parameters:
              compute_type: training
          - template: templates/${{ variables.version }}/deploy-training-pipeline.yml@mlops-templates
            parameters:
              enable_monitoring: $(enable_monitoring)
          - template: templates/${{ variables.version }}/add-pipeline-to-endpoint.yml@mlops-templates
          - template: templates/${{ variables.version }}/run-pipeline.yml@mlops-templates
